name: dashboard deploye

on:
  push:
    branches: [ main ]


jobs:
  dashboard-deploye:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run docker-compose
      run: docker-compose -f _cd.yaml up --build